version: '3'
services:
  cypress:
    # image: cypress/included:12.3.0
    working_dir: /usr/src/app
    volumes:
      - .:/e2e
    build:
      context: .
      dockerfile: Dockerfile
    command: ["cypress", "run"]
