version: '3'
services:
  cypress:
    image: cypress/included:12.3.0
    working_dir: /e2e
    volumes:
      - .:/e2e
    command: ["cypress", "run", "--spec", "cypress/e2e/cucumber/*.feature", "--browser", "chrome"]
